version: '3.6'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./local/mosquitto/:/mosquitto/config/:ro
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: {}